### ISSUE TITLE
Give it that also in Swift ?

### ISSUE THREAD

**Issue by Danielthenew** [ratulSharker/RSCustomTabbarController#1]
Hey first of all amazing Example, very cool :)

Have you make that example also in Swift ?

**Comment by ratulSharker** [comment]
Thanks @Danielthenew , **i'm bit new in swift**, i'm currently working some swift examples.

**Comment by Danielthenew** [comment]
Oke yeah was amazing when it give that example also in Swift. Oke then thanks for your replay.

**Comment by ratulSharker** [comment]
Hi @Danielthenew,
a demonstration in Swift is added in the latest master branch. Demonstration contain
- Tabbar Implementation
- TransitionAnimation implementaion

Let me know is everything ok with that, by leaving a comment.

**Comment by Danielthenew** [comment]
Hey thank you so much :) 
Yeah run very good.

**Comment by ratulSharker** [comment]
Okay then closing this issue.
